/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mipssim;

import javax.swing.JOptionPane;

/**
 *
 * @author hesha
 */
public class OtherBtns extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public OtherBtns() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// unchecked""
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 100, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Advanced");
		setBackground(new java.awt.Color(153, 153, 153));
		setLocation(new java.awt.Point(100, 100));
		setResizable(false);

		jButton1.setText("Speed up");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Milliseconds");
		jButton2.setText("Speed down");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Stop Running");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Mainy.start = false;
				Frame.Compile = true;
			}
		});

		jButton4.setText("Continue Running");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Mainy.start = true;
				Frame.Compile = false;
			}
		});

		jButton5.setText("Run Immediately");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Mainy.Speed = 0;
				jLabel2.setText(String.valueOf(Mainy.Speed) + " Milliseconds");

				if (Frame.Compile)
					Frame.RUNALL();

			}
		});

		jButton6.setText("Clear Registes");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				for (int i = 0; i < Mainy.Registers.RegArr.size(); i++)
					Mainy.Registers.RegArr.get(i).value = 0;

				JOptionPane.showMessageDialog(null, "Registers Cleared!", "", JOptionPane.PLAIN_MESSAGE);
			}
		});

		jButton7.setText("Clear memory");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				for (int i = 0; i < Programy.DataMem.length; i++)
					Programy.DataMem[i] = 0;

				JOptionPane.showMessageDialog(null, "Memory Cleared!", "", JOptionPane.PLAIN_MESSAGE);
			}
		});

		jButton8.setText("Clear All");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				for (int i = 0; i < Programy.DataMem.length; i++)
					Programy.DataMem[i] = 0;
				for (int i = 0; i < Mainy.Registers.RegArr.size(); i++)
					Mainy.Registers.RegArr.get(i).value = 0;

				JOptionPane.showMessageDialog(null, "Memory and Registers Cleared!", "", JOptionPane.PLAIN_MESSAGE);
			}
		});

		jLabel1.setText("Arguments in $a0, $a1, Result in $v0");

		jButton9.setText("Factorial");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Frame.Program.setText(
						"j exit1\nfact: addi $sp,$sp,-8\nsw $ra,4($sp)\nsw $a0,0($sp)\nslti $t0,$a0,1\nbeq $t0,$zero,L1\naddi $v0,$zero,1\naddi $sp,$sp,8\njr $ra\nL1: addi $a0,$a0,-1\njal fact\nlw $a0,0($sp)\nlw $ra,4($sp)\naddi $sp,$sp,8\nmul $v0,$a0,$v0\njr $ra\nexit1: jal fact");

				JOptionPane.showMessageDialog(null, "Number in $a0", "Tip", JOptionPane.PLAIN_MESSAGE);

			}
		});

		jButton10.setText("GCD Rec");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Frame.Program.setText(
						"j exit3\ngcd: addi $sp,$sp,-4\nsw $ra,0($sp)\nbeq $a0,$a1,exit1\nslt $t0,$a1,$a0\nbne $t0,$zero,L1\nsub $a1,$a1,$a0\njal gcd\nj exit2\nL1: sub $a0,$a0,$a1\njal gcd\nj exit2\nexit1: add $v0,$a0,$zero\nexit2: lw $ra,0($sp)\naddi $sp,$sp,4\njr $ra\nexit3: jal gcd");

				JOptionPane.showMessageDialog(null, "Numbers in $a0 and $a1, Result in $v0", "Tip",
						JOptionPane.PLAIN_MESSAGE);
			}
		});

		jButton11.setText("GCD non Rec");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Frame.Program.setText(
						"j exit1\ngcd: beq $a0,$a1,exit\nslt $t0,$a1,$a0\nbne $t0,$zero,L1\nsub $a1,$a1,$a0\nj gcd\nL1: sub $a0,$a0,$a1\nj gcd\nexit: add $v0,$a0,$zero\njr $ra\nexit1: jal gcd");

				JOptionPane.showMessageDialog(null, "Numbers in $a0 and $a1, Result in $v0", "Tip",
						JOptionPane.PLAIN_MESSAGE);
			}
		});

		jButton12.setText("Fibonacci");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Frame.Program.setText(
						"j exit1\nFIB: addi $t0,$zero,0\naddi $t1,$zero,1\nbeq $a0,$t0,L1\nbeq $a0,$t1,L2\naddi $sp,$sp,-12\nsw $ra,8($sp)\nsw $a0,4($sp)\nsw $s0,0($sp)\naddi $a0,$a0,-1\njal FIB\naddi $s0,$v0,0\naddi $a0,$a0,-1\njal FIB\nadd $v0,$v0,$s0\nlw $s0,0($sp)\nlw $a0,4($sp)\nlw $ra,8($sp)\naddi $sp,$sp,12\njr $ra\nL1: addi $v0,$zero,0\njr $ra\nL2: addi $v0,$zero,1\njr $ra\nexit1: jal FIB");

				JOptionPane.showMessageDialog(null, "Number in $a0, Result in $v0", "Tip", JOptionPane.PLAIN_MESSAGE);

			}
		});

		jButton13.setText("Insert Sort");
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Frame.Program.setText(
						"j exit1\ninsertSort: addi $t0,$0,1\nouterLoop: slt $t2,$t0,$a1\nbeq $t2,$0,end\nsll $t3,$t0,2\nadd $t3,$t3,$a0\nlw $t3,0($t3)\naddi $t1,$t0,-1\ninnerLoop: slt $t2,$t1,$0\nbne $t2,$0,exitInnerLoop\nsll $t2,$t1,2\nadd $t2,$t2,$a0\nlw $t2,0($t2)\nslt $t4,$t3,$t2\nbeq $t4,$0,exitInnerLoop\naddi $t5,$t1,1\nsll $t5,$t5,2\nadd $t5,$t5,$a0\nsw $t2,0($t5)\naddi $t1,$t1,-1\nj innerLoop\nexitInnerLoop: addi $t1,$t1,1\nsll $t1,$t1,2\nadd $t1,$t1,$a0\nsw $t3,0($t1)\naddi $t0,$t0,1\nj outerLoop\nend: jr $ra\nexit1: jal insertSort");

				JOptionPane.showMessageDialog(null, "Base address in $a0, array length in $a1", "Tip",
						JOptionPane.PLAIN_MESSAGE);

			}
		});

		jButton14.setText("Array sum");
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				Frame.Program.setText(
						"j ett\nsum: addi $v0,$zero,0\nsll $t0,$a1,2\nadd $t0,$a0,$t0\nL1: lw $t1,0($a0)\nadd $v0,$v0,$t1\naddi $a0,$a0,4\nslt $t2,$a0,$t0\nbne $t2,$zero,L1\njr $ra\nett: jal sum");
				JOptionPane.showMessageDialog(null, "Base address in $a0, array length in $a1, Result in $v0", "Tip",
						JOptionPane.PLAIN_MESSAGE);

			}
		});

		jLabel3.setText("Set of Programs");
		jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		jButton15.setText("Binary");
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Programy.ConvToBinary = true;
			}
		});

		jButton16.setText("Decimal");
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Programy.ConvToDec = true;
			}
		});

		jLabel4.setText("Datapath Output:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(44, 44, 44)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(34, 34, 34))
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addGap(18, 18, 18)))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton10).addComponent(jButton13).addComponent(jLabel3)))
						.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
				.addGap(18, 18, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton11)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton4).addComponent(jButton14)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
				.addContainerGap(16, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(40, 40, 40)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1)
						.addComponent(jButton2).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton4)
						.addComponent(jButton3).addComponent(jButton5))
				.addGap(23, 23, 23)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton7)
						.addComponent(jButton6).addComponent(jButton8))
				.addGap(24, 24, 24)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton15)
						.addComponent(jButton16).addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton9)
						.addComponent(jButton10).addComponent(jButton11))
				.addGap(31, 31, 31).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton12).addComponent(jButton13).addComponent(jButton14))
				.addContainerGap(29, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (Mainy.Speed < 2) {
			System.out.println("Clock Cycle is minimum");
			return;
		}
		Mainy.Speed -= 100;
		System.out.println("Clock Cycle: " + Mainy.Speed + " Milli Seconds");
		jLabel2.setText(String.valueOf(Mainy.Speed) + " Milliseconds");

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		Mainy.Speed += 100;
		System.out.println("Clock Cycle: " + Mainy.Speed + " Milli Seconds");
		jLabel2.setText(String.valueOf(Mainy.Speed) + " Milliseconds");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(OtherBtns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(OtherBtns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(OtherBtns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(OtherBtns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new OtherBtns().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration
}
